<?php

namespace App\Utils;

class Servers
{
    const LIST = [
        'Elemental' => [
            'Aegis',
            'Atomos',
            'Carbuncle',
            'Garuda',
            'Gungnir',
            'Kujata',
            'Ramuh',
            'Tonberry',
            'Typhon',
            'Unicorn'
        ],
        'Gaia' => [
            'Alexander',
            'Bahamut',
            'Durandal',
            'Fenrir',
            'Ifrit',
            'Ridill',
            'Tiamat',
            'Ultima',
            'Valefor',
            'Yojimbo',
            'Zeromus',
        ],
        'Mana' => [
            'Anima',
            'Asura',
            'Belias',
            'Chocobo',
            'Hades',
            'Ixion',
            'Mandragora',
            'Masamune',
            'Pandaemonium',
            'Shinryu',
            'Titan',
        ],
        'Aether' => [
            'Adamantoise',
            'Balmung',
            'Cactuar',
            'Coeurl',
            'Faerie',
            'Gilgamesh',
            'Goblin',
            'Jenova',
            'Mateus',
            'Midgardsormr',
            'Sargatanas',
            'Siren',
            'Zalera',
        ],
        'Primal' => [
            'Behemoth',
            'Brynhildr',
            'Diabolos',
            'Excalibur',
            'Exodus',
            'Famfrit',
            'Hyperion',
            'Lamia',
            'Leviathan',
            'Malboro',
            'Ultros',
        ],
        'Chaos' => [
            'Cerberus',
            'Lich',
            'Louisoix',
            'Moogle',
            'Odin',
            'Omega',
            'Phoenix',
            'Ragnarok',
            'Shiva',
            'Zodiark',
        ],
    ];
}
